version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user